version: "3.9"
services:
  playlist_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
  playlist-app:
    image: playlist-service
    ports:
      - "1000:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
    depends_on:
      - playlist_db
